# Windows-only asset generation; the game itself has no font or platform dependency.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$root = Split-Path $PSScriptRoot -Parent
$fontPath = Join-Path $root 'art-source/lettering/MaShanZheng-Regular.ttf'
$fonts = New-Object System.Drawing.Text.PrivateFontCollection
$fonts.AddFontFile($fontPath)
$glyphs = [ordered]@{}
try {
    foreach ($glyph in '曹关张马赵黄卒'.ToCharArray()) {
        $outline = New-Object System.Drawing.Drawing2D.GraphicsPath
        try {
            $outline.AddString([string]$glyph, $fonts.Families[0], 0, 1000,
                [System.Drawing.PointF]::new(0, 0), [System.Drawing.StringFormat]::GenericTypographic)
            $bounds = $outline.GetBounds()
            $points = $outline.PathPoints
            $types = $outline.PathTypes
            $commands = [System.Collections.Generic.List[object]]::new()
            for ($i = 0; $i -lt $points.Length; $i++) {
                $kind = $types[$i] -band 7
                $command = [System.Collections.Generic.List[object]]::new()
                $command.Add(@{0 = 'M'; 1 = 'L'; 3 = 'C'}[$kind])
                $count = if ($kind -eq 3) { 3 } else { 1 }
                for ($j = 0; $j -lt $count; $j++) {
                    $command.Add([math]::Round($points[$i + $j].X - $bounds.X, 2))
                    $command.Add([math]::Round($points[$i + $j].Y - $bounds.Y, 2))
                }
                $i += $count - 1
                $commands.Add($command.ToArray())
                if ($types[$i] -band 128) { $commands.Add(@('Z')) }
            }
            $glyphs[[string]$glyph] = @{
                w = [math]::Round($bounds.Width, 2)
                h = [math]::Round($bounds.Height, 2)
                paths = $commands.ToArray()
            }
        } finally { $outline.Dispose() }
    }
    $json = ConvertTo-Json -InputObject $glyphs -Depth 10 -Compress
    $source = "// Generated by tools/build-piece-lettering.ps1; do not edit outlines by hand.`n" +
        "// Ma Shan Zheng, Copyright 2018 The Ma Shan Zheng Project Authors. SIL OFL 1.1.`n" +
        "// License: assets/lettering/OFL.txt. Seven glyphs only; no runtime font loading.`n" +
        "module.exports = $json`n"
    [System.IO.File]::WriteAllText((Join-Path $root 'games/klotski/lettering-data.js'), $source,
        [System.Text.UTF8Encoding]::new($false))
} finally { $fonts.Dispose() }
